import {
  Location,
  AppUser,
  ServiceItem,
  ComboPackage,
  CustomerBooking,
  NamePlateSubscription,
  RevenueStats,
  AuditLog,
} from './types';

export const initialLocations: Location[] = [
  {
    id: 'LOC-1',
    name: 'South Peaceful Haven (HQ)',
    code: 'SPH-SOUTH',
    address: 'Plot 45, Green Valley Sector 12, South Region, City',
    phone: '+91 98765 00001',
    totalPlots: 60,
    occupiedPlots: 42,
    availablePlots: 18,
  },
  {
    id: 'LOC-2',
    name: 'North Paws Memorial Park',
    code: 'NPM-NORTH',
    address: 'Survey 102, Lake Road, North District, City',
    phone: '+91 98765 00002',
    totalPlots: 40,
    occupiedPlots: 28,
    availablePlots: 12,
  },
  {
    id: 'LOC-3',
    name: 'East Tranquil Pet Gardens',
    code: 'ETP-EAST',
    address: 'Highway 4, East Bypass Zone, City',
    phone: '+91 98765 00003',
    totalPlots: 35,
    occupiedPlots: 15,
    availablePlots: 20,
  }
];

export const initialUsers: AppUser[] = [
  {
    uid: 'USR-ADMIN-01',
    email: 'admin@cb-crm.com',
    displayName: 'Vikram Mehta (System Admin)',
    photoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=faces',
    role: 'ADMIN',
    status: 'ACTIVE',
  },
  {
    uid: 'USR-STAFF-01',
    email: 'staff.south@cb-crm.com',
    displayName: 'Suresh Kumar (South Operator)',
    photoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=faces',
    role: 'STAFF',
    assignedLocationId: 'LOC-1',
    status: 'ACTIVE',
  },
  {
    uid: 'USR-STAFF-02',
    email: 'staff.north@cb-crm.com',
    displayName: 'Ramesh Singh (North Operator)',
    photoURL: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=faces',
    role: 'STAFF',
    assignedLocationId: 'LOC-2',
    status: 'ACTIVE',
  }
];

export const initialServices: ServiceItem[] = [
  {
    id: 'SRV-101',
    name: 'Standard Burial Plot Service',
    description: 'Ground preparation, grave digging, basic casket lining, and burial ceremony.',
    price: 8000,
    category: 'BURIAL',
  },
  {
    id: 'SRV-102',
    name: '1-Year Pet Name Plate Subscription',
    description: 'Custom engraved metal name plate with tamper-evident QR code tag. Valid for 1 year.',
    price: 5000,
    category: 'NAME_PLATE',
    isSubscription: true,
  },
  {
    id: 'SRV-103',
    name: 'Individual Cremation & Urn',
    description: 'Private cremation with ceramic keepsake urn.',
    price: 9500,
    category: 'CREMATION',
  },
  {
    id: 'SRV-104',
    name: 'Annual Grave Maintenance & Flowers',
    description: 'Bi-monthly cleaning, fresh flower placement, and grass trimming for 1 year.',
    price: 3000,
    category: 'MAINTENANCE',
    isSubscription: true,
  },
  {
    id: 'SRV-105',
    name: 'Premium Teakwood Casket Upgrade',
    description: 'Handcrafted teakwood casket with velvet lining.',
    price: 4500,
    category: 'ADDON',
  },
];

export const initialCombos: ComboPackage[] = [
  {
    id: 'CMB-001',
    packageName: 'Standard Burial + 1-Year Name Plate Combo',
    description: 'Includes Ground Burial Plot Service (₹8,000) + 1-Year Scannable Name Plate Subscription (₹5,000).',
    bundledServiceIds: ['SRV-101', 'SRV-102'],
    totalOriginalPrice: 13000,
    comboPrice: 11500,
    savings: 1500,
    includesNamePlate: true,
    active: true,
  },
  {
    id: 'CMB-002',
    packageName: 'VIP Memorial Shrine & Teak Casket Package',
    description: 'Includes Burial Service (₹8,000) + Name Plate (₹5,000) + Teak Casket (₹4,500) + 1-Yr Maintenance (₹3,000).',
    bundledServiceIds: ['SRV-101', 'SRV-102', 'SRV-104', 'SRV-105'],
    totalOriginalPrice: 20500,
    comboPrice: 17500,
    savings: 3000,
    includesNamePlate: true,
    active: true,
  },
  {
    id: 'CMB-003',
    packageName: 'Eco Cremation & Memory Urn Package',
    description: 'Private cremation service (₹9,500) + Custom Memory Name Plate (₹5,000).',
    bundledServiceIds: ['SRV-103', 'SRV-102'],
    totalOriginalPrice: 14500,
    comboPrice: 13000,
    savings: 1500,
    includesNamePlate: true,
    active: true,
  },
];

export const initialBookings: CustomerBooking[] = [
  {
    id: 'BKG-9001',
    receiptNo: 'REC-2026-8801',
    locationId: 'LOC-1',
    locationName: 'South Peaceful Haven (HQ)',
    customerName: 'Rajesh Sharma',
    customerPhone: '+91 98765 43210',
    whatsappNumber: '+91 98765 43210',
    address: 'Flat 402, Sunshine Apartments, MG Road, South City',
    petName: 'Bruno',
    petType: 'Dog',
    petBreed: 'Golden Retriever',
    petAge: '8 Years',
    plotSector: 'Sector A',
    plotRow: 'Row A1',
    plotNumber: 'A1-05',
    selectedServiceIds: ['SRV-101', 'SRV-102'],
    selectedComboPackageId: 'CMB-001',
    totalAmount: 11500,
    paymentMethod: 'QR_CODE',
    paymentStatus: 'PAID',
    bookingDate: '2026-10-09',
    hasNamePlate: true,
    createdByStaff: 'Suresh Kumar',
  },
  {
    id: 'BKG-9002',
    receiptNo: 'REC-2026-8802',
    locationId: 'LOC-1',
    locationName: 'South Peaceful Haven (HQ)',
    customerName: 'Ananya Deshmukh',
    customerPhone: '+91 98123 99887',
    whatsappNumber: '+91 98123 99887',
    address: 'House 12, Park Street, South City',
    petName: 'Bella',
    petType: 'Cat',
    petBreed: 'Persian Cat',
    petAge: '4 Years',
    plotSector: 'Sector A',
    plotRow: 'Row A1',
    plotNumber: 'A1-08',
    selectedServiceIds: ['SRV-101', 'SRV-102'],
    selectedComboPackageId: 'CMB-001',
    totalAmount: 11500,
    paymentMethod: 'WHATSAPP_PAY_LINK',
    paymentStatus: 'PAID',
    bookingDate: '2026-10-09',
    hasNamePlate: true,
    createdByStaff: 'Suresh Kumar',
  },
  {
    id: 'BKG-9003',
    receiptNo: 'REC-2026-8803',
    locationId: 'LOC-2',
    locationName: 'North Paws Memorial Park',
    customerName: 'Karan Malhotra',
    customerPhone: '+91 99887 11223',
    whatsappNumber: '+91 99887 11223',
    address: 'Villa 88, Lake View Colony, North City',
    petName: 'Rocky',
    petType: 'Dog',
    petBreed: 'German Shepherd',
    petAge: '10 Years',
    plotSector: 'Sector B',
    plotRow: 'Row B2',
    plotNumber: 'B2-04',
    selectedServiceIds: ['SRV-101', 'SRV-102'],
    selectedComboPackageId: 'CMB-001',
    totalAmount: 11500,
    paymentMethod: 'CASH',
    paymentStatus: 'PAID',
    bookingDate: '2025-10-10',
    hasNamePlate: true,
    createdByStaff: 'Ramesh Singh',
  },
  {
    id: 'BKG-9004',
    receiptNo: 'REC-2026-8804',
    locationId: 'LOC-1',
    locationName: 'South Peaceful Haven (HQ)',
    customerName: 'Pooja Hegde',
    customerPhone: '+91 97654 00998',
    whatsappNumber: '+91 97654 00998',
    address: 'B-14, Green Enclave, South City',
    petName: 'Milo',
    petType: 'Dog',
    petBreed: 'Beagle',
    petAge: '6 Years',
    plotSector: 'Sector A',
    plotRow: 'Row A2',
    plotNumber: 'A2-02',
    selectedServiceIds: ['SRV-101', 'SRV-102'],
    selectedComboPackageId: 'CMB-001',
    totalAmount: 11500,
    paymentMethod: 'QR_CODE',
    paymentStatus: 'PAID',
    bookingDate: '2025-10-16',
    hasNamePlate: true,
    createdByStaff: 'Suresh Kumar',
  },
];

export const initialSubscriptions: NamePlateSubscription[] = [
  {
    id: 'SUB-5001',
    bookingId: 'BKG-9001',
    locationId: 'LOC-1',
    locationName: 'South Peaceful Haven (HQ)',
    tagSerial: 'NPT-88901',
    petName: 'Bruno',
    customerName: 'Rajesh Sharma',
    customerPhone: '+91 98765 43210',
    whatsappNumber: '+919876543210',
    plotSector: 'Sector A',
    plotNumber: 'A1-05',
    amountPaid: 5000,
    allotmentDate: '2026-10-09',
    expiryDate: '2027-10-09',
    daysUntilExpiry: 365,
    status: 'ALLOTTED_TODAY',
    isAllottedToday: true,
  },
  {
    id: 'SUB-5002',
    bookingId: 'BKG-9002',
    locationId: 'LOC-1',
    locationName: 'South Peaceful Haven (HQ)',
    tagSerial: 'NPT-88902',
    petName: 'Bella',
    customerName: 'Ananya Deshmukh',
    customerPhone: '+91 98123 99887',
    whatsappNumber: '+919812399887',
    plotSector: 'Sector A',
    plotNumber: 'A1-08',
    amountPaid: 5000,
    allotmentDate: '2026-10-09',
    expiryDate: '2027-10-09',
    daysUntilExpiry: 365,
    status: 'ALLOTTED_TODAY',
    isAllottedToday: true,
  },
  {
    id: 'SUB-5003',
    bookingId: 'BKG-9003',
    locationId: 'LOC-2',
    locationName: 'North Paws Memorial Park',
    tagSerial: 'NPT-77103',
    petName: 'Rocky',
    customerName: 'Karan Malhotra',
    customerPhone: '+91 99887 11223',
    whatsappNumber: '+919988711223',
    plotSector: 'Sector B',
    plotNumber: 'B2-04',
    amountPaid: 5000,
    allotmentDate: '2025-10-10',
    expiryDate: '2026-10-10',
    daysUntilExpiry: 1,
    status: 'EXPIRING_SOON',
  },
  {
    id: 'SUB-5004',
    bookingId: 'BKG-9004',
    locationId: 'LOC-1',
    locationName: 'South Peaceful Haven (HQ)',
    tagSerial: 'NPT-66104',
    petName: 'Milo',
    customerName: 'Pooja Hegde',
    customerPhone: '+91 97654 00998',
    whatsappNumber: '+919765400998',
    plotSector: 'Sector A',
    plotNumber: 'A2-02',
    amountPaid: 5000,
    allotmentDate: '2025-10-16',
    expiryDate: '2026-10-16',
    daysUntilExpiry: 7,
    status: 'EXPIRING_SOON',
  },
  {
    id: 'SUB-5005',
    bookingId: 'BKG-9005',
    locationId: 'LOC-1',
    locationName: 'South Peaceful Haven (HQ)',
    tagSerial: 'NPT-55105',
    petName: 'Coco',
    customerName: 'Sunil Shetty',
    customerPhone: '+91 91234 56780',
    whatsappNumber: '+919123456780',
    plotSector: 'Sector A',
    plotNumber: 'A2-06',
    amountPaid: 5000,
    allotmentDate: '2025-10-24',
    expiryDate: '2026-10-24',
    daysUntilExpiry: 15,
    status: 'EXPIRING_SOON',
  },
  {
    id: 'SUB-5006',
    bookingId: 'BKG-9006',
    locationId: 'LOC-2',
    locationName: 'North Paws Memorial Park',
    tagSerial: 'NPT-44106',
    petName: 'Leo',
    customerName: 'Dr. Sameer Roy',
    customerPhone: '+91 98989 77665',
    whatsappNumber: '+919898977665',
    plotSector: 'Sector B',
    plotNumber: 'B1-02',
    amountPaid: 5000,
    allotmentDate: '2025-11-05',
    expiryDate: '2026-11-05',
    daysUntilExpiry: 27,
    status: 'EXPIRING_SOON',
  },
  {
    id: 'SUB-5007',
    bookingId: 'BKG-9007',
    locationId: 'LOC-1',
    locationName: 'South Peaceful Haven (HQ)',
    tagSerial: 'NPT-33107',
    petName: 'Oscar',
    customerName: 'Meera Kapoor',
    customerPhone: '+91 97777 88888',
    whatsappNumber: '+919777788888',
    plotSector: 'Sector A',
    plotNumber: 'A3-01',
    amountPaid: 5000,
    allotmentDate: '2025-10-09',
    expiryDate: '2027-10-09',
    daysUntilExpiry: 365,
    status: 'RENEWED_TODAY',
    isRenewedToday: true,
  }
];

export const initialStats: RevenueStats = {
  todayCollection: 28000,
  sevenDaysCollection: 145000,
  fifteenDaysCollection: 290000,
  thirtyDaysCollection: 580000,
  totalAllottedToday: 2,
  totalRenewedToday: 1,
  expiringIn1Day: 1,
  expiringIn7Days: 2,
  expiringIn15Days: 3,
  expiringIn30Days: 4,
};


export const initialAuditLogs: AuditLog[] = [
  {
    id: 'AUD-501',
    locationId: 'LOC-1',
    tagSerial: 'NPT-88901',
    plotSector: 'Sector A',
    plotNumber: 'A1-05',
    scannedAt: '2026-10-09 11:30 AM',
    scannedBy: 'Vikram (Admin)',
    statusResult: 'ACTIVE',
    petName: 'Bruno',
    actionTaken: 'Verified Legit - Paid ₹5,000'
  },
  {
    id: 'AUD-502',
    locationId: 'LOC-1',
    tagSerial: 'NPT-UNKNOWN-999',
    plotSector: 'Sector A',
    plotNumber: 'A2-09',
    scannedAt: '2026-10-09 09:15 AM',
    scannedBy: 'Vikram (Admin)',
    statusResult: 'UNAUTHORIZED',
    petName: 'Unknown / Fake Plate',
    actionTaken: 'Flagged Illegal Installation - Staff Warning Issued',
    flaggedForRemoval: true
  }
];
